# Generated by Django 4.1.2 on 2022-11-25 16:22

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(error_messages={'unique': 'A Email with that Emails already exists.'}, max_length=254, verbose_name='Email')),
                ('telephone', models.IntegerField(verbose_name='Telephone number')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
