# Generated by Django 4.1.2 on 2022-12-19 12:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import shop.validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2), shop.validators.custom_validators.validate_only_letters], verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(error_messages={'unique': 'A Email with that Emails already exists.'}, max_length=254, unique=True, verbose_name='Email')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data joined')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
