# Generated by Django 4.1.2 on 2022-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
