# Generated by Django 4.1.2 on 2022-12-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='auth_user',
            field=models.BooleanField(default=False),
        ),
    ]
